### ISSUE TITLE
Overlay outline

### ISSUE THREAD

**Issue by EmilyLars** [muschellij2/neurobase#5]
Not an issue, more of a question/request: Is there a way to display an overlay image as simply an outline of the image (like with a mask)? I know the color and opacity can be altered but wondered if this was also possible. Thanks!

**Comment by muschellij2** [comment]
What do you mean the outline of any image?  You can dilate an image by a little and then take that subtraction of the dilation from the original image to get an "outline".  You can alternatively erode and image and subtract that image from the original image (one is bigger, one is smaller, depending on the intent) and then use `ortho2`.  Can you give me some more information on what you're trying to do.

**Comment by EmilyLars** [comment]
No worries I figured out how to do what I need with another tool. Thanks!
